#!/bin/sh

source ./src/common.sh

# Host name
HOST_NAME=`echo $1 | sed -e 's|^[^/]*//||' -e 's|/.*$||'`

# Download sites
./src/wget $HOST_NAME $1

# Compres sites
./src/zip $HOST_NAME

# Remove data
rm -r $DOWNLOAD_DIR/$HOST_NAME
