#!/bin/sh

source common.sh

docker run 																																		 \
	--rm 																																				 \
	-v /Users/macro/proyect/wget/download:/data 																 \
	mwendler/wget -S 																														 \
		--no-check-certificate 																										 \
		--recursive 																															 \
		--no-clobber 																															 \
		--page-requisites 																												 \
		--convert-links 																													 \
		--domains $1 																															 \
		-P /data/  																																 \
		$2
